const { chromium } = require(process.env.CLAMPDOWN_PLAYWRIGHT || "playwright");
const { build } = require("esbuild");
const { readFile, mkdir } = require("node:fs/promises");
const assert = require("node:assert/strict");
(async () => {
    await mkdir(".test-work/ui", { recursive: true });
    const bundle = await build({ entryPoints: ["test/ui-entry.cjs"], bundle: true, platform: "browser", write: false });
    const browser = await chromium.launch({ headless: true, executablePath: process.env.CLAMPDOWN_CHROME });
    try {
        const page = await browser.newPage({ viewport: { width: 1100, height: 900 } }); const errors = []; page.on("pageerror", e => errors.push(e.message));
        await page.setContent(await readFile("test/ui.html", "utf8")); await page.addScriptTag({ content: bundle.outputFiles[0].text });
        const composer = page.locator("button[data-clampdown]");
        const normal = await composer.evaluate(el => ({ color: getComputedStyle(el).color, background: getComputedStyle(el).backgroundColor, radius: getComputedStyle(el).borderRadius, duration: getComputedStyle(el).transitionDuration }));
        assert.equal(normal.radius, "8px"); assert.match(normal.duration, /0\.2s/);
        await composer.hover(); await page.waitForTimeout(250);
        const hovered = await composer.evaluate(el => ({ color: getComputedStyle(el).color, background: getComputedStyle(el).backgroundColor }));
        assert.notEqual(hovered.color, normal.color); assert.notEqual(hovered.background, normal.background);
        await composer.screenshot({ path: ".test-work/ui/composer-hover.png" });
        await page.mouse.move(0, 0); await page.waitForTimeout(250);
        assert.equal(await composer.evaluate(el => getComputedStyle(el).backgroundColor), normal.background);
        await composer.screenshot({ path: ".test-work/ui/composer-normal.png" });
        await page.getByRole("button", { name: "Open ClampDown", exact: true }).click();
        await page.getByRole("dialog").waitFor();
        await page.getByRole("group", { name: "Video compression preset" }).getByRole("button", { name: /Slow/ }).click();
        assert.equal(await page.evaluate(() => window.saved.videoPreset), "slow");
        await page.getByRole("group", { name: "Archive compression preset" }).getByRole("button", { name: /Ultra/ }).click();
        assert.equal(await page.evaluate(() => window.saved.archiveLevel), "9");
        await page.screenshot({ path: ".test-work/ui/quick.png" });
        await page.getByText("Advanced settings", { exact: true }).click();
        await page.getByLabel("Video codec", { exact: true }).selectOption("hevc"); assert.equal(await page.evaluate(() => window.saved.codec), "hevc");
        await page.getByLabel("Target size", { exact: true }).fill("5"); await page.getByLabel("Target size", { exact: true }).press("Tab"); assert.equal(await page.evaluate(() => window.saved.targetMiB), 5);
        await page.getByLabel("Archive part size", { exact: true }).fill("92"); await page.getByLabel("Archive part size", { exact: true }).press("Tab"); assert.equal(await page.evaluate(() => window.saved.archivePartPercent), 92);
        await page.getByText("Dependencies & setup", { exact: true }).click();
        await page.getByRole("button", { name: "Start local helper", exact: true }).click();
        await page.getByText("Local helper connected", { exact: true }).waitFor();
        await page.getByRole("button", { name: "Check Node.js", exact: true }).click();
        await page.getByText(/Node\.js v24\.20\.0/).waitFor();
        await page.getByRole("button", { name: "Download FFmpeg", exact: true }).click();
        await page.getByText("FFmpeg 9.0.1", { exact: true }).waitFor();
        await page.getByRole("button", { name: "Download 7-Zip", exact: true }).click();
        await page.getByText("7-Zip 26.03", { exact: true }).waitFor();
        await page.screenshot({ path: ".test-work/ui/dependencies.png" });
        await page.keyboard.press("Escape"); assert.equal(await page.getByRole("dialog").count(), 0);
        await page.setViewportSize({ width: 390, height: 844 });
        await page.getByRole("button", { name: "Open ClampDown", exact: true }).click();
        assert.ok(await page.getByRole("dialog").evaluate(el => el.scrollWidth <= el.clientWidth + 1));
        await page.screenshot({ path: ".test-work/ui/narrow.png" });
        await page.evaluate(() => window.showJobs());
        await page.getByRole("button", { name: "Cancel", exact: true }).click();
        assert.equal(errors.length, 0, errors.join("\n"));
        console.log("UI passed: preset persistence, advanced fields, dependency actions, Escape, narrow layout, cancellation, no browser errors.");
    } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
